export const ADD_STOCK = 'add_stock'
export const REMOVE_STOCK = 'remove_stock'
export const QUERY_DATA = 'query_data'
export const DATA_ARRIVED = 'data_arrived'
export const ERROR_HAPPEN = 'error_happend'